# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: 
    - cron: "3 3 * * SUN"
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  info-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: koushikphy
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Calcutta
          plugin_achievements: no
          plugin_lines: yes
          plugin_people: no
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          filename: info-metrics.svg

  achievements-metrics:
    runs-on: ubuntu-latest
    steps:

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: koushikphy
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 0
          plugin_achievements_only: polyglot,developer,stargazer,deployer,influencer,inspirer,contributor,automator,maintainer,follower
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          filename: achievements-metrics.svg